### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by ghost** [bubundas17/capacitor-nuxt-demo#1]
No matter what I do my app (Capacitor + Nuxt.JS) stays in the white loading screen when I open it (on Emulator and on Native android device). Your app is working but I can't see any differences with my app (beside the components). I hope you can help me. Maybe I missed something :/

**Comment by drmanhatin** [comment]
Did you ever figure this out?

**Comment by ghost** [comment]
I fixed it by changing the mode from 'universal' to 'spa', in the config file of Nuxt.js
